name: 'compile-badges-action'
description: '⚙️Save all your README badges as SVGs to save bandwidth'
author: 'Noah Koontz'
inputs:
  input_markdown_file:
    required: false
    description: The file to load and parse for badges to replace
    default: README.md
  output_markdown_file:
    required: false
    description: The file to write when parsing and replacing is complete
    default: README.md
  output_image_dir:
    required: false
    description: |
      The directory to write all the fetched badge SVGs to. This path must
      be relative and contained in the current repository.
    default: readme
  current_repository:
    required: false
    description: |
      The current repository in owner/name format. This value is used to
      generate URLs to raw.githubusercontent.com from a relative path in
      the repository. It is recommended this be left as the default value.
    default: ${{ github.repository }}
  current_branch:
    required: false
    description: |
      The current branch/ref in github.ref format. This value is used to
      generate URLs to raw.githubusercontent.com from a relative path in
      the repository. It is recommended this be left as the default value.
    default: ${{ github.ref }}
  badge_url_template:
    required: false
    description: |
      The template string used to generate URLs to the compiled badges.
      You can use this field to adjust which CDN this action should
      compile for (ex. githack instead of githubusercontent).

      This template is populated using the string-template library
      (https://www.npmjs.com/package/string-template) with the following
      available varibles:
       - `repo`: The string from the `current_repository` input.
       - `branch`: The branch name parsed from the `current_branch` input.
       - `path`: The path supplied by `ouput_image_dir` where badges
       are being stored. This path is automatically stripped of trailing
       slashes.
       - `badge`: The filename of the compiled badge output.
    default: https://raw.githubusercontent.com/{repo}/{branch}/{path}/{badge}

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: green
  icon: archive
